### ISSUE TITLE
Add support for messaging (error codes, tool numbers, etc)

### ISSUE THREAD

**Issue by Brianthechemist** [kethort/Mach4ModbusArduinoMegaW5500#8]
I'm planning to use this library to talk to the Arduino Machine Control board I got to control my tool changer (cheaper and faster than spinning a board for my Mega 2560 Pro).  

Is it possible to add functionality to send/receive registers in addition to coils?  I'd like to be able to send the message "tool #10" (obviously just the tool number as an int) to the arduino board.  

Perhaps this is a slight tweak of the ADC/DAC code.  I'll have to dig in more closely.

**Comment by kethort** [comment]
This repo was designed for input/output expansion via Modbus TCP using coils only, in Mach4. You can find examples of Modbus register use on the Mach4 forums, or if you are comfortable reading code, I have another example here: https://github.com/kethort/esp32-cnc-mpg-handwheel-conversion-mach4, where the encoder value, DRO's and Spindle/feedrates are sent using registers. 

There are also examples of reading and writing registers in the Arduino/examples folder of this repo.

**Comment by Brianthechemist** [comment]
Perfect. I can definitely work with that. I think the important stuff is
also there in the adc/dac examples.

**Comment by Brianthechemist** [comment]
Hi, I'm making great progress with the modbus stuff, thanks for the help.

I'm wondering if you could share the code you used to make this tab in
Mach: (maybe just send me your screenset, i can extract it I think.)

It looks like it would take forever to make using their screen editor!

[image: Mach4Modbus.PNG]

**Comment by kethort** [comment]
> Hi, I'm making great progress with the modbus stuff, thanks for the help. I'm wondering if you could share the code you used to make this tab in Mach: (maybe just send me your screenset, i can extract it I think.) It looks like it would take forever to make using their screen editor! [image: Mach4Modbus.PNG] On Tue, May 9, 2023 at 4:46 PM Brian Sparano ***@***.***> wrote:
> […](#)

The profiles included in Mach4 Profiles folder have the tab in them. Just run main Mach4 launcher and select import profile. You’ll also need to copy the wxForms.lua file in the Modules directory to the C:/Mach4Hobby/Modules folder

**Comment by Brianthechemist** [comment]
Awesome thanks!
